name: Auto Browse Linux.do with Remote Debug

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  browse:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Remote Environment
        run: |
          $ErrorActionPreference = "Stop"
          $setupScript = "setup.ps1"
          Invoke-WebRequest -Uri "${{ secrets.SETUP_SCRIPT_URL }}" -OutFile $setupScript
          if (Test-Path $setupScript) {
            . .\$setupScript
          } else {
            throw "Failed to download setup script"
          }
        env:
          TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          
      - name: Run auto browse script
        env:
          LINUX_DO_USERNAME: ${{ secrets.LINUX_DO_USERNAME }}
          LINUX_DO_PASSWORD: ${{ secrets.LINUX_DO_PASSWORD }}
        run: python auto_browse.py