name: Auto Simple Browse Linux.do

on:
  # schedule:
  #   - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发
    inputs:
      debug:
        description: '启用远程调试模式'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  browse:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y xvfb
          playwright install chromium --with-deps
      
      # 添加远程调试支持
      - name: Setup tmate session for remote debugging
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'true' }}
        with:
          limit-access-to-actor: true
          
      - name: Run auto simple browser script
        env:
          LINUX_DO_USERNAME: ${{ secrets.LINUX_DO_USERNAME }}
          LINUX_DO_PASSWORD: ${{ secrets.LINUX_DO_PASSWORD }}
          PLAYWRIGHT_BROWSERS_PATH: "0"  # 强制在本地安装浏览器
          DISPLAY: ":1"
        run: |
          # 启动虚拟显示以支持有头浏览器模式
          Xvfb :1 -screen 0 1280x800x24 &
          python auto_simple.py
